# Generated by Django 3.2 on 2023-03-06 14:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Areas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(default='', max_length=80)),
                ('estadoReg', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Cargos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(default='', max_length=80)),
                ('estadoReg', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cedula', models.CharField(default='', max_length=30)),
                ('nombre', models.CharField(default='', max_length=150)),
                ('salario', models.DecimalField(decimal_places=2, max_digits=15)),
                ('fechaIngreso', models.DateTimeField(default=django.utils.timezone.now)),
                ('fechaRetiro', models.DateTimeField(default=django.utils.timezone.now)),
                ('contraseña', models.CharField(default='', max_length=20)),
                ('estadoReg', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', max_length=1)),
                ('area', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='aSreas', to='tickets.areas')),
            ],
        ),
        migrations.CreateModel(
            name='Sedes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codreg_sede', models.CharField(default='', max_length=30)),
                ('nom_sede', models.CharField(default='', max_length=30)),
                ('codreg_ips', models.CharField(default='', max_length=30)),
                ('direccion', models.CharField(default='', max_length=200)),
                ('telefono', models.CharField(default='', max_length=120)),
                ('departamento', models.CharField(default='', max_length=120)),
                ('municipio', models.CharField(default='', max_length=120)),
                ('zona', models.CharField(default='', max_length=120)),
                ('sede', models.CharField(default='', max_length=120)),
                ('estadoReg', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', max_length=1)),
            ],
            options={
                'unique_together': {('codreg_sede', 'nom_sede')},
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('cedula', models.CharField(default='', max_length=30)),
                ('estadoReg', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', max_length=1)),
                ('sede', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sSedes_0', to='tickets.sedes')),
                ('ticket', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tTicket', to='tickets.ticket')),
            ],
        ),
        migrations.CreateModel(
            name='TiposCargos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(default='', max_length=80)),
                ('estadoReg', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='TiposEmpleadosPerfil',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(default='', max_length=80)),
                ('estadoReg', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='TiposEmpresa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigoEmpresa', models.CharField(default='', max_length=1)),
                ('nombre', models.CharField(default='', max_length=30)),
                ('estadoReg', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='TiposTicket',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(default='', max_length=30)),
                ('estadoReg', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='TiposTurno',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(default='', max_length=30)),
                ('desde', models.CharField(default='', max_length=30)),
                ('hasta', models.CharField(default='', max_length=30)),
                ('estadoReg', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Ubicaciones',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(default='', max_length=80)),
                ('estadoReg', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='TicketsDetalle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('desdeInicial', models.DateTimeField(default=django.utils.timezone.now)),
                ('hastaInicial', models.DateTimeField(default=django.utils.timezone.now)),
                ('desdeFinal', models.DateTimeField(default=django.utils.timezone.now)),
                ('hastaFinal', models.DateTimeField(default=django.utils.timezone.now)),
                ('adjunto', models.CharField(default='', max_length=120)),
                ('textoRespuesta', models.CharField(default='', max_length=200)),
                ('estadoRespuesta', models.CharField(choices=[('Aprobado', 'Aprobado'), ('Rechazado', 'Rechazado'), ('Pendiente', 'Pendiente')], default='P', max_length=9)),
                ('estadoReg', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', max_length=1)),
                ('reemplazo', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tEmpleados_1', to='tickets.empleados')),
                ('respuestaEmpleadoPerfil', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ttiposEmpleados_1', to='tickets.tiposempleadosperfil')),
                ('sede', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sSedes_7', to='tickets.sedes')),
                ('sedeFinal', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sSedes_3', to='tickets.sedes')),
                ('sedeInicial', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sSedes_1', to='tickets.sedes')),
                ('sedeReemplazo', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sSedes_5', to='tickets.sedes')),
                ('ticket', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tTicket_1', to='tickets.ticket')),
                ('tiposTicket', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ttiposTicket_1', to='tickets.tiposticket')),
                ('tiposTurnoFinal', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ttiposTurnos_2', to='tickets.tiposturno')),
                ('tiposTurnoInicial', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ttiposTurnos_1', to='tickets.tiposturno')),
            ],
        ),
        migrations.AddField(
            model_name='ticket',
            name='tiposTicket',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ttiposTicket', to='tickets.tiposticket'),
        ),
        migrations.AddField(
            model_name='empleados',
            name='cargo',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ccargos', to='tickets.tiposcargos'),
        ),
        migrations.AddField(
            model_name='empleados',
            name='empresa',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ttiposEmpresas', to='tickets.tiposempresa'),
        ),
        migrations.AddField(
            model_name='empleados',
            name='sede',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sSedes', to='tickets.sedes'),
        ),
        migrations.AddField(
            model_name='empleados',
            name='tiposEmpleadoPerfil',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ttiposEmpleadosPerfil', to='tickets.tiposempleadosperfil'),
        ),
        migrations.AddField(
            model_name='empleados',
            name='tiposTurno',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ttiposTurnos_3', to='tickets.tiposturno'),
        ),
        migrations.AddField(
            model_name='empleados',
            name='ubicacion',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='uubicaciones', to='tickets.ubicaciones'),
        ),
    ]
