# Generated by Django 3.2 on 2023-03-06 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleados',
            name='cargo',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ttiposEmpleadosPerfil_1', to='tickets.tiposempleadosperfil'),
        ),
        migrations.DeleteModel(
            name='TiposCargos',
        ),
    ]
