# Generated by Django 3.2 on 2023-03-10 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_auto_20230306_1030'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticketsdetalle',
            old_name='estadoRespuesta',
            new_name='estadoRespuestaCoordinador',
        ),
        migrations.RenameField(
            model_name='ticketsdetalle',
            old_name='textoRespuesta',
            new_name='textoRespuestaCoordinador',
        ),
        migrations.RemoveField(
            model_name='ticketsdetalle',
            name='respuestaEmpleadoPerfil',
        ),
        migrations.AddField(
            model_name='areas',
            name='sedes',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ssedes', to='tickets.sedes'),
        ),
        migrations.AddField(
            model_name='ticketsdetalle',
            name='estadoRespuestaDueño',
            field=models.CharField(choices=[('Aprobado', 'Aprobado'), ('Rechazado', 'Rechazado'), ('Pendiente', 'Pendiente')], default='P', max_length=9),
        ),
        migrations.AddField(
            model_name='ticketsdetalle',
            name='estadoRespuestaThumano',
            field=models.CharField(choices=[('Aprobado', 'Aprobado'), ('Rechazado', 'Rechazado'), ('Pendiente', 'Pendiente')], default='P', max_length=9),
        ),
        migrations.AddField(
            model_name='ticketsdetalle',
            name='respuestaEmpleadoCoordinador',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='eempleados_1', to='tickets.empleados'),
        ),
        migrations.AddField(
            model_name='ticketsdetalle',
            name='respuestaEmpleadoDueño',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='eempleados_3', to='tickets.empleados'),
        ),
        migrations.AddField(
            model_name='ticketsdetalle',
            name='respuestaEmpleadoThumano',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='eempleados_2', to='tickets.empleados'),
        ),
        migrations.AddField(
            model_name='ticketsdetalle',
            name='textoRespuestaDueño',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='ticketsdetalle',
            name='textoRespuestaThumano',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='ubicaciones',
            name='sedes',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ssedes2', to='tickets.sedes'),
        ),
    ]
