# Generated by Django 3.2 on 2023-03-15 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_mallaturnos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleados',
            name='area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='aSreas', to='tickets.areas'),
        ),
        migrations.AlterField(
            model_name='empleados',
            name='cargo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ttiposEmpleadosPerfil_1', to='tickets.cargos'),
        ),
        migrations.AlterField(
            model_name='empleados',
            name='empresa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ttiposEmpresas', to='tickets.tiposempresa'),
        ),
        migrations.AlterField(
            model_name='empleados',
            name='sede',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sSedes', to='tickets.sedes'),
        ),
        migrations.AlterField(
            model_name='empleados',
            name='tiposEmpleadoPerfil',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ttiposEmpleadosPerfil', to='tickets.tiposempleadosperfil'),
        ),
        migrations.AlterField(
            model_name='empleados',
            name='tiposTurno',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ttiposTurnos_3', to='tickets.tiposturno'),
        ),
        migrations.AlterField(
            model_name='empleados',
            name='ubicacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='uubicaciones', to='tickets.ubicaciones'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='sede',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sSedes_0', to='tickets.sedes'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tTicket', to='tickets.ticket'),
        ),
        migrations.AlterField(
            model_name='ticketsdetalle',
            name='reemplazo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tEmpleados_1', to='tickets.empleados'),
        ),
        migrations.AlterField(
            model_name='ticketsdetalle',
            name='respuestaEmpleadoCoordinador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='eempleados_1', to='tickets.empleados'),
        ),
        migrations.AlterField(
            model_name='ticketsdetalle',
            name='respuestaEmpleadoDueño',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='eempleados_3', to='tickets.empleados'),
        ),
        migrations.AlterField(
            model_name='ticketsdetalle',
            name='respuestaEmpleadoThumano',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='eempleados_2', to='tickets.empleados'),
        ),
        migrations.AlterField(
            model_name='ticketsdetalle',
            name='sede',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sSedes_7', to='tickets.sedes'),
        ),
        migrations.AlterField(
            model_name='ticketsdetalle',
            name='sedeFinal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sSedes_3', to='tickets.sedes'),
        ),
        migrations.AlterField(
            model_name='ticketsdetalle',
            name='sedeInicial',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sSedes_1', to='tickets.sedes'),
        ),
        migrations.AlterField(
            model_name='ticketsdetalle',
            name='sedeReemplazo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sSedes_5', to='tickets.sedes'),
        ),
        migrations.AlterField(
            model_name='ticketsdetalle',
            name='ticket',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tTicket_1', to='tickets.ticket'),
        ),
        migrations.AlterField(
            model_name='ticketsdetalle',
            name='tiposTicket',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ttiposTicket_1', to='tickets.tiposticket'),
        ),
        migrations.AlterField(
            model_name='ticketsdetalle',
            name='tiposTurnoFinal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ttiposTurnos_2', to='tickets.tiposturno'),
        ),
        migrations.AlterField(
            model_name='ticketsdetalle',
            name='tiposTurnoInicial',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ttiposTurnos_1', to='tickets.tiposturno'),
        ),
    ]
