# Generated by Django 3.2 on 2023-03-15 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_rename_contraseña_empleados_contrasena'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='ticket',
        ),
    ]
