# Generated by Django 3.2 on 2023-03-16 12:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_remove_ticket_ticket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketsdetalle',
            name='ticket',
        ),
        migrations.AddField(
            model_name='ticketsdetalle',
            name='cedula',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='ticketsdetalle',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.DeleteModel(
            name='Ticket',
        ),
    ]
