# Generated by Django 3.2 on 2023-03-16 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0009_auto_20230316_0741'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TicketsDetalle',
            new_name='Tickets',
        ),
    ]
