# Generated by Django 3.2 on 2023-03-16 21:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0010_rename_ticketsdetalle_tickets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='desdeInicial',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='hastaInicial',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
