# Generated by Django 3.2 on 2023-03-17 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0014_rename_cedula_tickets_empleado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='reemplazo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tEmpleados_1', to='tickets.empleados'),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='respuestaEmpleadoThumano',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='eempleados_2', to='tickets.empleados'),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='sedeFinal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sSedes_3', to='tickets.sedes'),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='sedeReemplazo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sSedes_5', to='tickets.sedes'),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='tiposTurnoFinal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ttiposTurnos_2', to='tickets.tiposturno'),
        ),
    ]
