# Generated by Django 3.2 on 2023-03-17 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0015_auto_20230317_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='adjunto',
            field=models.FileField(upload_to='Uploaded Files/'),
        ),
    ]
