# Generated by Django 3.2 on 2023-03-17 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0016_alter_tickets_adjunto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='adjunto',
            field=models.FileField(blank=True, null=True, upload_to='Uploaded Files/'),
        ),
    ]
