# Generated by Django 3.2 on 2023-03-17 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0017_alter_tickets_adjunto'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='visibleTicketEmpledo',
            field=models.CharField(choices=[('S', 'Si'), ('N', 'No')], default='A', max_length=1),
        ),
    ]
