# Generated by Django 3.2 on 2023-03-17 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0019_rename_visibleticketempledo_tickets_visibleticketempleado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='visibleTicketEmpleado',
            field=models.CharField(choices=[('S', 'Si'), ('N', 'No')], default='N', max_length=1),
        ),
    ]
