# Generated by Django 3.2 on 2023-03-17 19:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0020_alter_tickets_visibleticketempleado'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiposticket',
            name='abrev',
            field=models.CharField(blank=True, choices=[('V', 'Vacaciones'), ('I', 'Incapacidad'), ('P', 'Permiso'), ('R', 'Reemplazo'), ('T', 'Traslado Sede'), ('C', 'Calamidad'), ('L', 'Licencia Remunerada'), ('N', 'Licencia No remunerada'), ('X', 'Cambio de Turno')], max_length=1, null=True),
        ),
        migrations.CreateModel(
            name='TicketsMalla',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('dia', models.CharField(blank=True, max_length=5, null=True)),
                ('abrev', models.CharField(blank=True, choices=[('V', 'Vacaciones'), ('I', 'Incapacidad'), ('P', 'Permiso'), ('R', 'Reemplazo'), ('T', 'Traslado Sede'), ('C', 'Calamidad'), ('L', 'Licencia Remunerada'), ('N', 'Licencia No remunerada'), ('X', 'Cambio de Turno')], max_length=1, null=True)),
                ('estadoReg', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', max_length=1)),
                ('empleado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='eempleados_5', to='tickets.empleados')),
                ('mallaTurnos', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mmalla1', to='tickets.mallaturnos')),
                ('ticket', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tticket1', to='tickets.tickets')),
            ],
        ),
    ]
