# Generated by Django 3.2 on 2023-03-29 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0021_auto_20230317_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='asignado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tEmpleados_7', to='tickets.empleados'),
        ),
        migrations.AlterField(
            model_name='areas',
            name='sedes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ssedes', to='tickets.sedes'),
        ),
        migrations.AlterField(
            model_name='empleados',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='aSreas', to='tickets.areas'),
        ),
        migrations.AlterField(
            model_name='empleados',
            name='cargo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ttiposEmpleadosPerfil_1', to='tickets.cargos'),
        ),
        migrations.AlterField(
            model_name='empleados',
            name='sede',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sSedes', to='tickets.sedes'),
        ),
        migrations.AlterField(
            model_name='empleados',
            name='tiposTurno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ttiposTurnos_3', to='tickets.tiposturno'),
        ),
        migrations.AlterField(
            model_name='empleados',
            name='ubicacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='uubicaciones', to='tickets.ubicaciones'),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eempleados1', to='tickets.empleados'),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='sede',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sSedes_7', to='tickets.sedes'),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='sedeInicial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sSedes_1', to='tickets.sedes'),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='tiposTicket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ttiposTicket_1', to='tickets.tiposticket'),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='tiposTurnoInicial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ttiposTurnos_1', to='tickets.tiposturno'),
        ),
        migrations.AlterField(
            model_name='ubicaciones',
            name='sedes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ssedes2', to='tickets.sedes'),
        ),
    ]
