# Generated by Django 3.2 on 2023-03-29 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0022_auto_20230329_0730'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tickets',
            name='sede',
        ),
    ]
