# Generated by Django 3.2 on 2023-04-03 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0024_auto_20230329_0805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='estadoRespuestaCoordinador',
            field=models.CharField(choices=[('Aprobado', 'Aprobado'), ('Rechazado', 'Rechazado'), ('Pendiente', 'Pendiente')], default='Pendiente', max_length=9),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='estadoRespuestaDueño',
            field=models.CharField(choices=[('Aprobado', 'Aprobado'), ('Rechazado', 'Rechazado'), ('Pendiente', 'Pendiente')], default='Pendiente', max_length=9),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='estadoRespuestaThumano',
            field=models.CharField(choices=[('Aprobado', 'Aprobado'), ('Rechazado', 'Rechazado'), ('Pendiente', 'Pendiente')], default='Pendiente', max_length=9),
        ),
    ]
