# Generated by Django 3.2 on 2023-04-03 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0025_auto_20230403_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='mallaturnos',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='aareas_2', to='tickets.areas'),
        ),
    ]
