# Generated by Django 3.2 on 2023-04-03 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0026_mallaturnos_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mallaturnos',
            name='dia1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ttTiposTurno_1', to='tickets.tiposturno'),
        ),
        migrations.AlterField(
            model_name='mallaturnos',
            name='dia10',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ttTiposTurno_10', to='tickets.tiposturno'),
        ),
        migrations.AlterField(
            model_name='mallaturnos',
            name='dia11',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ttTiposTurno_11', to='tickets.tiposturno'),
        ),
        migrations.AlterField(
            model_name='mallaturnos',
            name='dia12',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ttTiposTurno_12', to='tickets.tiposturno'),
        ),
        migrations.AlterField(
            model_name='mallaturnos',
            name='dia13',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ttTiposTurno_13', to='tickets.tiposturno'),
        ),
        migrations.AlterField(
            model_name='mallaturnos',
            name='dia14',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ttTiposTurno_14', to='tickets.tiposturno'),
        ),
        migrations.AlterField(
            model_name='mallaturnos',
            name='dia15',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ttTiposTurno_15', to='tickets.tiposturno'),
        ),
        migrations.AlterField(
            model_name='mallaturnos',
            name='dia16',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ttTiposTurno_16', to='tickets.tiposturno'),
        ),
        migrations.AlterField(
            model_name='mallaturnos',
            name='dia17',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ttTiposTurno_17', to='tickets.tiposturno'),
        ),
        migrations.AlterField(
            model_name='mallaturnos',
            name='dia18',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ttTiposTurno_18', to='tickets.tiposturno'),
        ),
        migrations.AlterField(
            model_name='mallaturnos',
            name='dia19',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ttTiposTurno_19', to='tickets.tiposturno'),
        ),
        migrations.AlterField(
            model_name='mallaturnos',
            name='dia2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ttTiposTurno_2', to='tickets.tiposturno'),
        ),
        migrations.AlterField(
            model_name='mallaturnos',
            name='dia20',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ttTiposTurno_20', to='tickets.tiposturno'),
        ),
        migrations.AlterField(
            model_name='mallaturnos',
            name='dia21',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ttTiposTurno_21', to='tickets.tiposturno'),
        ),
        migrations.AlterField(
            model_name='mallaturnos',
            name='dia22',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ttTiposTurno_22', to='tickets.tiposturno'),
        ),
        migrations.AlterField(
            model_name='mallaturnos',
            name='dia23',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ttTiposTurno_23', to='tickets.tiposturno'),
        ),
        migrations.AlterField(
            model_name='mallaturnos',
            name='dia24',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ttTiposTurno_24', to='tickets.tiposturno'),
        ),
        migrations.AlterField(
            model_name='mallaturnos',
            name='dia25',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ttTiposTurno_25', to='tickets.tiposturno'),
        ),
        migrations.AlterField(
            model_name='mallaturnos',
            name='dia26',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ttTiposTurno_26', to='tickets.tiposturno'),
        ),
        migrations.AlterField(
            model_name='mallaturnos',
            name='dia27',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ttTiposTurno_27', to='tickets.tiposturno'),
        ),
        migrations.AlterField(
            model_name='mallaturnos',
            name='dia28',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ttTiposTurno_28', to='tickets.tiposturno'),
        ),
        migrations.AlterField(
            model_name='mallaturnos',
            name='dia29',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ttTiposTurno_29', to='tickets.tiposturno'),
        ),
        migrations.AlterField(
            model_name='mallaturnos',
            name='dia3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ttTiposTurno_3', to='tickets.tiposturno'),
        ),
        migrations.AlterField(
            model_name='mallaturnos',
            name='dia30',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ttTiposTurno_30', to='tickets.tiposturno'),
        ),
        migrations.AlterField(
            model_name='mallaturnos',
            name='dia31',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ttTiposTurno_31', to='tickets.tiposturno'),
        ),
        migrations.AlterField(
            model_name='mallaturnos',
            name='dia4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ttTiposTurno_4', to='tickets.tiposturno'),
        ),
        migrations.AlterField(
            model_name='mallaturnos',
            name='dia5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ttTiposTurno_5', to='tickets.tiposturno'),
        ),
        migrations.AlterField(
            model_name='mallaturnos',
            name='dia6',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ttTiposTurno_6', to='tickets.tiposturno'),
        ),
        migrations.AlterField(
            model_name='mallaturnos',
            name='dia7',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ttTiposTurno_7', to='tickets.tiposturno'),
        ),
        migrations.AlterField(
            model_name='mallaturnos',
            name='dia8',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ttTiposTurno_8', to='tickets.tiposturno'),
        ),
        migrations.AlterField(
            model_name='mallaturnos',
            name='dia9',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ttTiposTurno_9', to='tickets.tiposturno'),
        ),
    ]
