# Generated by Django 3.2 on 2023-04-03 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0027_auto_20230403_1500'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mallaturnos',
            old_name='año',
            new_name='ano',
        ),
    ]
