# Generated by Django 3.2 on 2023-04-03 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0028_rename_año_mallaturnos_ano'),
    ]

    operations = [
        migrations.AddField(
            model_name='mallaturnos',
            name='estadoReg',
            field=models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', max_length=1),
        ),
    ]
