# Generated by Django 3.2 on 2023-04-03 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0029_mallaturnos_estadoreg'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiposturno',
            name='abrev',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='tiposturno',
            name='desde',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='tiposturno',
            name='hasta',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
