# Generated by Django 3.2 on 2023-04-03 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0030_auto_20230403_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mallaturnos',
            name='estadoReg',
            field=models.CharField(blank=True, choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', max_length=1, null=True),
        ),
    ]
