# Generated by Django 3.2 on 2023-04-03 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0032_alter_mallaturnos_estadoreg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mallaturnos',
            name='estadoReg',
        ),
    ]
