# Generated by Django 3.2 on 2023-04-03 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0033_remove_mallaturnos_estadoreg'),
    ]

    operations = [
        migrations.AddField(
            model_name='mallaturnos',
            name='estadoReg',
            field=models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', max_length=1),
        ),
    ]
