# Generated by Django 3.2 on 2023-04-20 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0035_alter_mallaturnos_estadoreg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tickets',
            old_name='estadoRespuestaDueño',
            new_name='estadoRespuestaDueno',
        ),
        migrations.RenameField(
            model_name='tickets',
            old_name='respuestaEmpleadoDueño',
            new_name='respuestaEmpleadoDueno',
        ),
        migrations.RenameField(
            model_name='tickets',
            old_name='textoRespuestaDueño',
            new_name='textoRespuestaDueno',
        ),
    ]
