# Generated by Django 3.2 on 2023-04-26 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0036_auto_20230420_1439'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketsmalla',
            name='abrev',
        ),
        migrations.RemoveField(
            model_name='ticketsmalla',
            name='dia',
        ),
    ]
